### ISSUE TITLE
Cargo should give helpful errors when unsupported flags are used.

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/cargo#11702]
### Problem

There are several flags one might imagine users passing to Cargo that aren't supported _yet_. It'd be nice if we told users who try to use these what to use instead, and perhaps also linked to the issue (if any) proposing to add such a flag. Some examples:

- [x] There's no `-C` for running in a different directory. (blocked on #11957)
- [x] There's no `-w` or `-W` short for `--workspace` (except in `update`, blocked on #11554).
- [x] There's no `-x` for `--exclude` #12805
- [x] There's no `-t` for `--target` #12805
- [x] There's no `-s` for `--quiet` (`-s` is "silent" in `curl`)  https://github.com/rust-lang/cargo/pull/12723
- [ ] It's `--manifest-path`, not `--path` (though there _is_ `--path` for `cargo add`)
- [x] There's no `-c` for `--config` https://github.com/rust-lang/cargo/pull/12777
- [x] There's no `-z`, only `-Z` #12788
- [x] There's no `-O`, only `--out-dir` https://github.com/rust-lang/cargo/pull/12755
- [x] There's no `-n` for `--dry-run` https://github.com/rust-lang/cargo/pull/12660

**Comment by weihanglo** [comment]
Does it make sense having this as a built-in mechanism in clap for suggesting an alternative flag?

**Comment by epage** [comment]
@weihanglo I think that can make sense to seed clap with specific suggestions and not just rely on the automatic suggestions and that would help simplify things for application, like cargo.  Mind opening an issue?

**Comment by weihanglo** [comment]
More examples:

- There's no `--debug` for `cargo build`. Only `--release`.
- There's no `--release` for `cargo install`. Only `--debug`.

These does confuse people a lot. See #12009.

**Comment by weihanglo** [comment]
I am not sure if we should wait for upstream fix or make our own custom suggestion. Let's label it as waiting for upstream first. We still **seek a ad-hoc solution for each case** if somebody is interested in.

@rustbot label +S-blocked-external

**Comment by weihanglo** [comment]
https://github.com/clap-rs/clap/pull/5075 just got landed with [clap@4.3.22](https://crates.io/crates/clap/4.3.22). People, we now can have basic suggestions for unsupported arguments!

I'll write down a list of flags of interest and instructions shortly.

@rustbot label -S-blocked-external +S-accepted +E-easy

**Comment by weihanglo** [comment]
Not sure if this is the relevant clap issue <https://github.com/clap-rs/clap/issues/4853>. Supposed we are going to leverage `UnknownArgumentValueParser` for those well-known unknown arguments, it might cause unwanted typo suggestion for them.

Let me label it blocked on that issue at this moment.

@rustbot label -S-accepted +S-blocked-external

**Comment by epage** [comment]
@weihanglo could you give an example of where that causes a problem worth blocking this issue?

**Comment by weihanglo** [comment]
Something like this? Though for short aliases clap doesn't suggest them I feel like. If that's the case we can continue working on short aliases part.


```console
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
     Running `target/debug/cargo install --please`
error: unexpected argument '--please' found

  tip: a similar argument exists: '--release'

Usage: cargo install --release [crate]...

For more information, try '--help'.
```

**Comment by epage** [comment]
Asking to better characterize the problem: is that always bad though?

Take the prior work in #12529, like `cargo test --keep-going`.  If the user thought it should work and did `cargo test --keep-goign`, today they would get a correction and then be pointed to the correct flag (yes, ideally the two steps would be one step which might be a consideration where `suggest_arg` is appropriate).  With the proposed change, the user would just get an `unexpected argument` error and would fall back to `--help`.  Trying to understand which path is best.

**Comment by weihanglo** [comment]
It's not inherently bad, and agree with that two steps is better than infinite steps searching in `--help`. Just it is lying that “a similar argument exists”, which doesn't.

I am convinced that it's not really a blocker 😆. Would be great if clap can improve the situation.

@rustbot label +S-accepted -S-blocked-external
