### ISSUE TITLE
Tracking Issue for trim-paths RFC 3127

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#12137]
### Summary

RFC: [#3127](https://github.com/rust-lang/rfcs/pull/3127)
Documentation: https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#profile-trim-paths-option
Issues: https://github.com/rust-lang/cargo/labels/Z-trim-paths
rustc tracking issue: https://github.com/rust-lang/rust/issues/111540

This adds a new profile setting (among other things) to control how paths are sanitized in the resulting binary.

### Unresolved Issues

* [ ] (non-blocking) Should make `--remap-path-prefix` work with `rustdoc` and doctest?
  * Yes as rustdoc supports both
    * https://github.com/rust-lang/rust/pull/107099
    * https://github.com/rust-lang/rust/pull/128736
  * [x] Integrate `--remap-path-prefix` in rustdoc invocations (`cargo doc`) https://github.com/rust-lang/cargo/pull/14389
  * [ ] Integrate `--remap-path-prefix` and `-Zremap-path-scope` in doctest (`cargo test --doc`)
* [x] Determine the remap rules: https://github.com/rust-lang/cargo/issues/13171
  * [x] A cross-platform stable hash for `CARGO_HOME` layout? https://github.com/rust-lang/cargo/pull/14917
    * [x] On Windows the local path contains prefix component e.g.`C:/`, which essentially results in a different hash result from what on other platforms. This is unlikely to be resolved.
    * [x] benchmark BLAKE3, BLAKE2s, and rustc-stable-hasher
       * See result in <https://github.com/rust-lang/cargo/pull/14116#issuecomment-2486293308>
       * rustc-stable-hash is on par with the original siphash, while blake3 is 2-3x slower. The total spent in stable hashing for a `cargo build` invocation may be unimportant. It took 500μs-1500μs for buidling cargo itself.
    * [x] This is the final remap rules: https://github.com/rust-lang/cargo/pull/17302
    * [x] To help user to unremap back, an unremap file is added as an companion files of binaries: https://github.com/rust-lang/cargo/pull/17303 
* [ ] Should workspace member paths in trimmed artifacts stay relative, or get a virtual prefix like dependencies?
  * Relative keeps the common case easy, for example, debuggers resolve workspace sources with zero configuration
  * Relative also introduces a second *mechanism* for consumers (prefix substitution vs. relative-join). For example, symbolication pipelines need two code paths https://github.com/rust-lang/cargo/pull/17366#issuecomment-5303319051
  * Non-blocking as we have unremap file `.trim-paths.jsonl` records `workspace_root`.
  * Ask about this trade-off during call-for-testing
* [x] There should be some tests for Windows and macOS
    * [x] windows-gnu https://github.com/rust-lang/cargo/pull/17221/
    * [x] windows-msvc https://github.com/rust-lang/cargo/pull/15621
    * [x] macOS https://github.com/rust-lang/cargo/pull/13118
    * [x] Be sure to consider the impact of back versus forward slashes, and whether or not that will work with either
      * As of 84a7a403847019436b99266e592464a495d316da, GDB accepts either; CDB requires backslashes
* [x] Support `CARGO_TRIM_PATHS_SCOPE` and `CARGO_TRIM_PATHS_REMAP` in build-rs crate
    * https://github.com/rust-lang/cargo/pull/17104#discussion_r3414716812
    * https://github.com/rust-lang/cc-rs/pull/1794
* [ ] Unremap files
  * (non-blocking) Currently Cargo only generates unremap files for root units. Should this be extended to artifact dependencies? https://github.com/rust-lang/cargo/pull/17303#discussion_r3706646233
  * The schema of the unremap file. See https://github.com/rust-lang/cargo/pull/17303#discussion_r3706668858
* [ ] (non-blocking) Interact with `-Zroot-dir`
  * https://github.com/rust-lang/cargo/pull/17337#issuecomment-5227072820
* [ ] (non-blocking) build-rs new API for `CARGO_TRIM_PATHS_REMAP` and `CARGO_TRIM_PATHS_SCOPE`

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Implementation history

* https://github.com/rust-lang/cargo/pull/12625
* https://github.com/rust-lang/cargo/pull/12900
* https://github.com/rust-lang/cargo/pull/12908
* https://github.com/rust-lang/cargo/pull/14389
* https://github.com/rust-lang/cargo/pull/14908
* https://github.com/rust-lang/cargo/pull/15614
* https://github.com/rust-lang/cargo/pull/17104
* https://github.com/rust-lang/cargo/pull/17302
* https://github.com/rust-lang/cargo/pull/17303
* https://github.com/rust-lang/cargo/pull/17337
* https://github.com/rust-lang/cargo/pull/17338
* https://github.com/rust-lang/cargo/pull/17349
* https://github.com/rust-lang/cargo/pull/17366
* https://github.com/rust-lang/cargo/pull/17424
* https://github.com/rust-lang/cargo/pull/17425
* https://github.com/rust-lang/cargo/pull/17432
* https://github.com/rust-lang/cargo/pull/17476

**Comment by epage** [comment]
Last status update I'm aware of

https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/trim-paths.20testing/near/401425246

**Comment by joshtriplett** [comment]
Is this working on Linux, well enough that we could ship it for Linux without promising macOS support?

**Comment by weihanglo** [comment]
This is the latest status of it on rustc side: <https://github.com/rust-lang/rust/issues/111540#issuecomment-2014748609>, which the new remap rule in [the conclusion](https://github.com/rust-lang/rust/issues/111540#issuecomment-1994010274) is implemented. I've updated the unresolved issues section in this tracking issue.

**Comment by weihanglo** [comment]
Status update:

* This change <https://github.com/rust-lang/rust/pull/107099> should make `-Ztrim-paths` also work for rustdoc
* A stable hasher extracting from rustc is on its way. See also
  * https://github.com/rust-lang/compiler-team/issues/755
  * https://github.com/rust-lang/rustc-stable-hash/pull/1

**Comment by weihanglo** [comment]
https://github.com/rust-lang/rust/pull/107099 is just merged, so should be able to support for rustdoc.

**Comment by weihanglo** [comment]
Updated:

* doctest has supported remapping: https://github.com/rust-lang/rust/pull/122450
* rustdoc diagnostics hasn't: <https://github.com/rust-lang/rust/issues/69264#issuecomment-2261945619>

That potentially blocks this, if we would like to see `-Ztrim-paths` supports also for rustdoc invocations.

**Comment by liciana24** [comment]
> Updated:
> 
> * doctest has supported remapping: [Simplify trim-paths feature by merging all debuginfo options together rust#122450](https://github.com/rust-lang/rust/pull/122450)
> * rustdoc diagnostics hasn't: [rustdoc: use remap-path-prefix rust#69264 (comment)](https://github.com/rust-lang/rust/issues/69264#issuecomment-2261945619)
> 
> That potentially blocks this, if we would like to see `-Ztrim-paths` supports also for rustdoc invocations.

both of those linked are closed/merged what is left blocking to get trimpaths working?

**Comment by weihanglo** [comment]
> both of those linked are closed/merged what is left blocking to get trimpaths working?

@liciana24 There are some unresolved issues listed in the PR description I just updated.

It should minimally work. Any feedback of it not working?

**Comment by lina9992006** [comment]
status?

**Comment by weihanglo** [comment]
@lina9992006 
Just posted benchmark results here: https://github.com/rust-lang/cargo/pull/14116#issuecomment-2486293308

If you'd like to move this forward, here are areas we need helps:

* Resolving issues mentioned in the PR description.
* Testing out the current implementation and provide feedback.

**Comment by lina9992006** [comment]
why is hashing relevant here?

**Comment by weihanglo** [comment]
A stable cross-platform hash algorithm helps `-Ztrim-paths` finding sources from the same path when debugging. See <https://github.com/rust-lang/cargo/issues/13171#issuecomment-1864899037> and other comments around.

**Comment by weihanglo** [comment]
Given [the bootstrap integration](https://github.com/rust-lang/rust/pull/161049) is about to merge, I am considering stabilization for this feature. Some things we probably want to do before stabilization

* [ ] Agree on the remap rules
  * [#t-cargo > stabilization plan for &#96;-Ztrim-paths&#96; @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/246057-t-cargo/topic/stabilization.20plan.20for.20.60-Ztrim-paths.60/near/621134084)
* [ ] Agree on the unremap file schema (the `.trim-paths.jsonl`)
  * [#t-cargo > stabilization plan for &#96;-Ztrim-paths&#96; @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/246057-t-cargo/topic/stabilization.20plan.20for.20.60-Ztrim-paths.60/near/621134184)
* [x] Stabilization only `true|"all"`, `false|"none"` and `"object"` options for `profile.trim-paths`, as they are likely most used options. Others can be deferred
  * https://github.com/rust-lang/cargo/pull/17432
* [x] Remove the implicit `"object"` default for `trim-paths` for the `release` profile. We shouldn't change the default value in the same edition
  * https://github.com/rust-lang/cargo/pull/17424
* [x] Document or refer to [rustc doc](https://doc.rust-lang.org/nightly/rustc/remap-source-paths.html) about the limitation
  * So far executables tier-1 platforms like Windows and Linux are host-path-leaks-free, while macOS leaks through OSO stub (see <https://github.com/rust-lang/rust/issues/116948>). However, macOS binary can be leak-free if applying with these profile settings (while dSYM bundle is still leaking):
    ```toml
    debug = true
    trim-paths = "object"
    split-debuginfo = "packed"
    strip = "debuginfo"
    ```
    * https://github.com/rust-lang/cargo/pull/17425
* [ ] After addressing the above, we write a call-for-testing for about test leaking and debugging experience. We should be more precise and honest about the expectation.

Does this stabilization plan look reasonable?

**Comment by epage** [comment]
One wrinkle I've been meaning to write up about. We have a unit hash / fingerprint hack for RUSTFLAGS that I think deals with the intersection of pgo and remap rules. iirc the current rules have the unit hash when dealing with a build scripts out dir. Is it possible to resolve this or are there updates needed for the profile way of applying remap rules?

**Comment by weihanglo** [comment]
Could you be more specific what the wrinkile is?

I guess you are referring to [this hack](https://github.com/rust-lang/cargo/blob/1cc3200205e66761af709831ffa62f071a06c512/src/compiler/build_runner/compilation_files.rs#L892-L904) for reproducibility and PGO:

* For PGO we don't want `--remap-path-prefix` to get into `-Cmetadata` hash, to keep the symbol name stable
* For reproducibilty, we don't want `--remap-path-prefix` to get into `-Cextra-filename` hash

For `profile.trim-paths`  we has the profile setting value, not the actual rustflags, I think it works well. As for manually supplied `RUSTFLAGS=--remap-path-prefix` we probably need a transition period after the stabilization of `trim-paths`, and we remove the hack.

Or, are you wrinkle in something like `-Cprofile-use=/abs/path/to/merged.profdata` that might affect unit id hash?

**Comment by epage** [comment]
> For profile.trim-paths we has the profile setting value, not the actual rustflags,

Profile settings go into both `-Cmetadata` and `Cextra-filename` according to https://doc.rust-lang.org/nightly/nightly-rustc/cargo/compiler/fingerprint/index.html

I don't remember enough about the original problem. Is the problem what you are mapping from being in those which won't be in the profile hash, which should make this safe?

**Comment by weihanglo** [comment]
Yes, that is my understanding. Cargo computed absolute remap paths won't get into any of those hashes, which is safe.

**Comment by weihanglo** [comment]
## Call for testing

We are preparing to stabilize Cargo's new [`profile.trim-paths` setting](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#profile-trim-paths-option).

The `trim-paths` option controls the scope of path sanitization in build outputs. Before stabilization, we are looking for real world feedback about path leaks and debugging experience.

### Requirements

Use `nightly-2026-09-06` or later:

```console
$ cargo +nightly --version
cargo 1.100.0-nightly (3c0b53475 2026-09-04)
```

Create `.cargo/config.toml` at your Cargo workspace root:

```toml
[unstable]
trim-paths = true

[profile.release]
trim-paths = "object" # or `"all"`
debug = true # Recommended when testing debugger support.
```

Then build your project normally:

```console
$ cargo +nightly build --release
```

### What to test

We are particularly interested in the following stuff:

* Whether final executables/artifacts still contain unexpected absolute paths from the workspace, `CARGO_HOME`, rustup toolchain, macros, or build directory.

* Whether debugging works with the unremap file `<artifact>.trim-paths.jsonl`, like setting breakpoints, stepping, source display, and backtrace inspections.
  * Nightly `rust-gdb` and `rust-lldb` bundled with the Rust toolchain will load them automatically if environment variable `RUST_GDB_TRIM_PATHS=unstable` or `RUST_LLDB_TRIM_PATHS=unstable` is set.
  * We also want to call for testing on Windows debugging particularly.

* Whether if there are any quirks with projects using like build scripts, generated source, native deps, custom linkers, cross-compilation, or staticlib.

* Whether `trim-paths` causes problems for diagnostics, editors, rustdoc, and build caches.
  * It is known that `trim-paths="all"` remaps diagnostcis so IDE would fail to open remapped file links
  * Also sccache doesn't yet exclude `--remap-path-prefix` <https://github.com/mozilla/sccache/issues/2765>.

* If you maintain debuggers or sympolication tools. Whether your tools work well with relative path remaps, or a virtual workspace prefix would be easier to consume. `trim-paths` currently remaps workspace sources as relative paths, such as `./src/main.rs`. 

* While this is not aimed at full reproducibility in Cargo, the sanitized binaries are expected to be fairly reproducible. We'd like to know how your caching tools/systems works or don't work with it, and what the gap is in reproducibility

For known limitation, see <https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#limitations>.

We are looking forward to both successful and failing cases.
Would be great if the report includes the output of `cargo -vV`, target, linker, selected trim-paths value, and a reproduction when possible. Thank you for helping the CfT.

**Comment by U007D** [comment]
This RFC will appear in the **Call for Testing** section of the next issue (issue 669) of This Week in Rust (TWiR).  You may remove the `call-for-testing` label.  Please feel free to leave the `call-for-testing` label in place if you would like this RFC to appear again in another issue of TWiR.
