### ISSUE TITLE
User control over cargo warnings

### ISSUE THREAD

**Issue by epage** [rust-lang/cargo#12235]
### Problem

Today, cargo maintainers are very cautious as to what warnings are created because they cannot be turned off by the user when they are intended.  The problem is we've not had a mechanism to control it.  With #12115, we'll now have a mechanism

Turning existing warnings into lints:
- #11782
- Publish size warnings (https://github.com/rust-lang/rfcs/pull/3397#discussion_r1213330487)
- #7380
- Control the warning from #10910
- #2568
- <https://github.com/rust-lang/cargo/issues/15964>

Porting clippy lints to cargo
- #4377 (see also [clippy::cargo_common_metadata](https://rust-lang.github.io/rust-clippy/master/index.html#cargo_common_metadata))
- #5340 (see also [clippy::wildcard_dependencies](https://rust-lang.github.io/rust-clippy/master/index.html#/wildcard_dependencies?groups=cargo), [deny::wildcard](https://embarkstudios.github.io/cargo-deny/checks/bans/diags.html#wildcard))
- #13899 (see also [clippy::multiple_crate_versions](https://rust-lang.github.io/rust-clippy/master/index.html#/multiple_crate_versions?groups=cargo), [deny::duplicate](https://embarkstudios.github.io/cargo-deny/checks/bans/diags.html#duplicate))
- #15581
- #15580

Examples of new lints:
- #4413 ([deny::detected-executable](https://embarkstudios.github.io/cargo-deny/checks/bans/diags.html#detected-executable), [deny::detected-executable-script](https://embarkstudios.github.io/cargo-deny/checks/bans/diags.html#detected-executable-script))
- #4300
- #9058
- Warn on old build-directive syntax (#11461)
- Warn in more cases than #10910
- Maybe #2489
- Disable warning from path dependencies #8546
- Warn on mixed case package names (#6043)
- #7081
- #2039 (see also rust-lang/rust-clippy#3867, [deny's licenses](https://embarkstudios.github.io/cargo-deny/checks/licenses/diags.html))
- #6003
- #4611
- #5890
- #7760
- #6827
- Redundant `package.homepage` (see #13293)
- #15578
- #15579
- non-latest edition
- #14390
- warn if two dep info files within the same package point to the same source file (#7730).
- deny missing metadata when running `cargo package` https://github.com/rust-lang/cargo/issues/15398#issuecomment-2781116158

### Proposed Solution

As package and workspace level lint control, turning existing warnings into diagnostics where possible

Tasks
- [x] rustc-like diagnostics for parsing `Cargo.toml` (#13172)
- [x] Report what set the lint level (see #13778 for context)
- [x] `im_a_teapot` lint should be unstable (see #13797 for context) (implemented in #13805)
- [x] Clean up forbid handling for default/edition level (see #13797 for context)
- [x] Documentation of all supported lints similar to [`rustc`](https://doc.rust-lang.org/rustc/lints/index.html) and [`clippy`](https://rust-lang.github.io/rust-clippy/stable/index.html) (see #14025)
- [x] Needs a stable lint at the time of stabilization
  - #16374, #16373
  - #15871
  - #15586
  - #15579
- [x] Warning, error count
  - Report as part of existing summaries?
- [x] `build.warnings` control (#17112)
- [x] report all errors, not just first, in parse pass (#17095)
- [ ] Which sub-diagnostic the lint level reason goes into?
- [ ] Audit `unwrap`
- [x] Make paths relative in the same way as rustc diagnostics (#17101)
- [x] #16982
- [ ] Lints for unstable features (made difficult by lack of runtime iteration of `-Z`) (what should be the behavior of lints for runtime controlled unstable features like `hint-mostly-unused`, always run or only with `-Z`)
- [x] Document writing of lints' (#17090)
  - First group is primary, all others are secondary
  - Emitted reason is last element of primary group
  - Emitted reason is only emitted once per package
  - (TBD) Helps without snippets may be elements of the primary group, otherwise make them secondary groups
    - Never do a help as an annotation's label
  - When OR-ing of help messages, use a common prefix to help clarify that for users
  - If can't provide a `Snippet` (e.g. in-memory manifests), at least provide an `Origin`
  - Follow rustc's dev guide on grammar, etc
  - Rules on padding?
- [ ] Deterministic order of linting packages
- [x] How to handle false positives from `unused_dependencies` (#16600).  Started with an `ignored = ["dep_name]`, then ignoring `direct & transitive` (#16935, #16937)

Non-blocking
- rustc-like diagnostics for parsing `Cargo.lock`
- rustc-like diagnostics for parsing `.cargo/config.toml`
- Deciding how to handle edition compatibility groups and groups in general (since #13740 skipped it for 2024)
  - Should we reuse rustc groups or not?
- rustc-like diagnostics for processing `Cargo.toml` (ie port warnings off of `shell.warn` for consistency)
- Diagnostic summary
- Paths are not relative to the same root as rustc's

Rejected
- `_::warnings` dynamic group (`rust` or `cargo`?): specialized warning for specific workflows that is being superseded by other mechanisms

Open questions
- [x] How many of the lints should be run as part of every cargo invocation vs run as part of an explicit "lint" step?
  - See https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/Cargo.20Lints/near/389419039
  - Every invocation for now as decided at the All Hands
- [x] Do we share namespaces when appropriate?
  - See https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/Sharing.20of.20lints/near/475872847
  - No, at All Hands we decided that Cargo should operate on its own lints only
- [x] Where should workspace-level lints run?  On the workspace or on each package?
  - Run them on the workspace, subject to the `workspace.lints` (with a sometimes fallback to `lints` similar to `*.resolver`)

### Notes

There will still be lints that are not related to the package but related to the user or / invocation.  At a later stage, we can consider user-level lint levels.

Showing lint reason once per package:
- When inherited, we could potentially show it once per workspace just like rustc would do for a crate level attribute
- Starting with this now as an MVP, we can always re-evaluate later

Deferred reducing boilerplate

Deferred json messages

Deferred: whether to make lint docs more like clippy

Out of scope: CLI control.  That would be evaluated for `[lints]` as a whole, potentially through config.  Note that existing runtime lint control is not officially supported in Cargo but done through an escape hatch

**Comment by epage** [comment]
From https://github.com/rust-lang/cargo/issues/10160#issuecomment-1573883951

> Just had a talk with @Muscraft. This is mostly my idea but it would be great if we have this kind of error overhaul. It will help things like JSON format message (#8283) or developing Cargo's own lint rules with `-Zlints` (#12115). It would also open a door to diagonostics translation ([rust-lang/rust#100717](https://github.com/rust-lang/rust/issues/100717)). Probably the modularization of Cargo could benefit from it as well.

**Comment by epage** [comment]
imo we need structured diagnostics which we pass to the diagnostic system which will then be turned into errors or something else

**Comment by epage** [comment]
An obvious way to implement this is to shove the lint config in and our of `Config` as we enter and leave the relevant contexts.  This is a bit more brittle and lowers our chances for doing some operations with threading as `Config` needs to be mutable everywhere

One thought for how we could implement this
- Rename `Config` to `Context` (we might want to do this anyways)
- Refactor `Context` to allow decorating it (wrapping it)
- Whenever we start down a workspace or package specific code path, we decorate the `Context` with that workspace or package's lint configuration

**Comment by epage** [comment]
One thought I had from #13621 was more about the linting system as a whole.

Should we use `cargo::rust_2024_compatibility` group or should we key off of `rust::rust_2024_compatibility` group?

**Comment by epage** [comment]
Take `unused_lints`.  iirc `rust::unused_lints` affects both rustc and clippy.

So the question would be
- Is `rust::unused_lints` global or specialized for `rustc` linters
- If not global, does that mean `cargo::unused_lints` should affect all `Cargo.toml` linters (e.g. if we moved Cargo lints from `clippy-driver` to `cargo clippy`)

Or put another way, does a user say "I want to see 2024 Edition compatibility warnings" or do they say "I want to see Rust 2024 Edition compatibility warnings separately from Cargo 2024 Edition compatibility warnings".  The Edition is the same concept, so it seems weird to split it by tool.  However, rustfmt does have a distinct Edition so maybe we should keep it more loose generally?

**Comment by BenjaminBrienen** [comment]
Edit: nevermind, the command is `cargo check`

```
 techn0@IO  ~/source/wgsl-analyzer   main ±  cargo +nightly lint -Zcargo-lints
warning: /home/techn0/source/wgsl-analyzer/crates/syntax/Cargo.toml: unused manifest key `lints.cargo` (may be supported in a future version)

consider passing `-Zcargo-lints` to enable this feature.
warning: /home/techn0/source/wgsl-analyzer/xtask/Cargo.toml: unused manifest key `lints.cargo` (may be supported in a future version)
```

maybe this warning should only be shown on the Cargo.toml where it is inheriting this key from. These tomls only have `workspace.lints = true`.
