### ISSUE TITLE
Tracking Issue for `-Zlockfile-path`

### ISSUE THREAD

**Issue by weihanglo** [rust-lang/cargo#14421]
### Summary

Original issue: #5707
Implementation: #14326
Documentation: https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#lockfile-path

The `-Zlockfile-path` flag enables the `resolver.lockfile-path` configuration option,
which allows you to specify the path of the lockfile `Cargo.lock`.

### Unresolved Issues

- [ ] Inconsistency in `resolver` table being applied to `cargo install`
- [ ] How this should work if the lockfile or a parent directory is not present
  - In [#14326], missing parent directories will be created when Cargo is about to write the lockfile. This minimizes the chance of creating dangling directories. 
- [ ] `cargo install --lockfile-path=<path>` implies `--locked`, and requires the alternative lockfile to exist.
  - This behavior diverges from other commands, which allow the absence of lockfile at the alternative path.
- [x] #15510

[#14326]: https://github.com/rust-lang/cargo/pull/14326

### Tasks

- [x] Add an unstable doc under <https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#lockfile-path> #14423
- [x] `cargo install` should make `--lockfile-path` imply `--locked` #14556
- [x] Add support for `resolver.lockfile-path` in #16510
- [x] Expand `resolver.lockfile-path` coverage in #16617
- [ ] Remove `--lockfile-path` in 1.95.0-nightly

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

**Comment by Ifropc** [comment]
As far as shell completions go, I don't think we need to do anything in the scope of this task. In fact, it's alreadyready working on the latest nightly (as part of https://github.com/rust-lang/cargo/issues/14520)
![Image](https://github.com/user-attachments/assets/2846f465-4c09-4169-8e33-b146c757e2da)

**Comment by epage** [comment]
@Ifropc thats the new, unstable completion system.

The task is referring to our handwritten, stable completions
- https://github.com/rust-lang/cargo/blob/master/src/etc/_cargo
- https://github.com/rust-lang/cargo/blob/master/src/etc/cargo.bashcomp.sh

**Comment by Ifropc** [comment]
Got it, I will add the support into the stable system + will do the lock filter in the new system. Thought the unstable stuff is automatically grouped into the unstable autocomplete system as well, but guess it's a separate matter.
Thanks Ed!

**Comment by epage** [comment]
#16510 changed this from a CLI flag to a config field.  See also #15510

**Comment by ifropc** [comment]
Great job team!!
