### ISSUE TITLE
Reduce the need for users to write build scripts

### ISSUE THREAD

**Issue by epage** [rust-lang/cargo#14948]
Like RUSTFLAGS, build scripts are an important escape hatch.  Like RUSTFLAGS (#12739), we should find replacements for common uses of build scripts so people don't have to reach to this escape hatch so often

Reducing build scripts would
- Improve build times
- Reduce risk of bugs
- Reduce the dependency review audit scope

Uses of build scripts
- [ ] Version detection
  - Stabilizing rust-lang/rust#64797
  - Stabilizing rust-lang/rust#64796
- [ ] Making `cfg` values available at runtime (e.g. in `--bugreport`, `--version`, or crash reports, or for tests building examples)
  - Possibly provide `cfg_value!`, `cfg_values!`, `try_cfg_value!`, `try_cfg_values!` (see also [mutually exclusive features](https://internals.rust-lang.org/t/pre-rfc-mutually-excusive-global-features/19618))
- [ ] Making `TARGET` available at runtime (e.g. `--version`, building examples in tests)
- [ ] Codegen
  - [using tests](https://matklad.github.io/2022/03/26/self-modifying-code.html)
  - #12552
- [ ] [cfg_aliases](https://docs.rs/cfg_aliases/latest/cfg_aliases/)
  - see also https://github.com/rust-lang/cargo/issues/14948#issuecomment-2581426536)
  - see also https://github.com/rust-lang/rfcs/pull/3804
- [ ] Feature warnings (deprecations, a feature being "disabled" due to a platform or another feature, etc)
  - see also https://github.com/rust-lang/rfcs/pull/3486
- [ ] Catch-all: rust-lang/cargo#14903
  - Note: this would also allow consolidating the ecosystem which would help with baking-in more features to replace build scripts
  - Enable linker warnings on Windows
  - Embedded windows manifests (#16328)
  - Can we use this for `-sys` crates / FFI?

**Comment by ChrisDenton** [comment]
I would draw a distinction between main binary build scripts (e.g. the executable or cdylib) and libraries. I think a build scripts for an executable is far more tolerable than for libraries. They're in direct control of the crate author and don't have any other users. Also a single top-level build script is going to have negligible impact on build times for all but the smallest projects.

Which is not to say they're not important too, just that reducing the need for library build scripts will likely have the far bigger impact.

**Comment by epage** [comment]
This is not about trying to remove all build scripts but finding patterns in the community and providing a solution to avoid writing one yourself. In some cases, this will be using an artifact dependency as your build script. This is a general solution that helps libs and bins. And the benefits extend to bins. For smaller projects it democratizes the benefits of build scripts by making it easier to discover what you can do, easier to implement, and with fewer bugs. For larger projects with multiple bins, it makes reuse easier, reduces build times, and makes it easier to audit your own code base.

Yes, libs will get more benefits as we prioritize solutions to implement but understanding and tracking the needs of bins takes little away from that but instead gives a better understanding for designing soluations.

**Comment by kamulos** [comment]
I don't know if this is important enough, but I also have a small use-case: I integrate a version string from an environment variable into my program during compile time. A natural way to do this would be the `env!()` macro, but this will not rebuild if the env variable changes.

So I am forced to use a build script with the `cargo::rerun-if-env-changed` declaration.

**Comment by bjorn3** [comment]
`env!()` should rebuild when the env var changes. We changed rustc to record which env vars are read using `env!()` into the dep info file years ago and at the same time changed cargo to rebuild crates when env vars mentioned in the dep info file changes.

**Comment by kamulos** [comment]
Oh that works! 😊 I don't know what went wrong the last time I tested it, sorry for the confusion.

**Comment by epage** [comment]
Cargo might not fully track its own env variables which would be a bug.

iirc `try_env!` does not report env variables for tracking, at least if they aren't there.

**Comment by weihanglo** [comment]
> Cargo might not fully track its own env variables which would be a bug.
> 
> iirc `try_env!` does not report env variables for tracking, at least if they aren't there.

Did you mean [`option_env!`](https://doc.rust-lang.org/nightly/std/macro.option_env.html)? They're also tracked by `# env-dep:` comment in rustc dep-info files.

**Comment by nicoburns** [comment]
Can we add "cfg aliases" to this list (i.e. what is implemented using a build script by the https://docs.rs/cfg_aliases/latest/cfg_aliases/ crate)?

Winit is a prominent crate that depends on this `cfg_aliases`, and from a Dioxus/Blitz perspective I understand why they've done this. We have `cfg` expressions that spread to [6 lines](https://github.com/DioxusLabs/blitz/blob/main/packages/dioxus-native/src/dioxus_application.rs#L31C13-L36C16) or [more](https://github.com/DioxusLabs/dioxus/blob/main/packages/dioxus/src/launch.rs#L28).

Use cases where this is commonly comes up are where there is functionality that works on N of M platforms (e.g. 3 of 6), that you also want to be controllable with a feature flag (users may or may not want the function), and that you want to be disabled on platforms where it doesn't work even when the feature is enabled (as otherwise it becomes burdensome for users to set platform-specific features (where this is even possible)).

To give an entirely concrete example. In [blitz-shell](https://github.com/DioxusLabs/blitz/tree/main/packages/blitz-shell) we use [muda](https://github.com/tauri-apps/muda) for implementing system menus on windows/macos/linux(desktop), but this functionality isn't available and doesn't make sense on android/ios/web. We also wish to make it optional on platforms that do support it. So we need a feature flag AND platform-specific `cfg`s, which ends up being a lot of boilerplate.

It would be nice if we could define aliases (either in `lib.rs` or `Cargo.toml`) and then use a simple `#[cfg(menu)]`.

**Comment by epage** [comment]
@nicoburns I've added `cfg_aliases`.  An intermediate solution would be to stabilize metadeps and then you could declare `cfg_aliases` as one of your build scripts, passing parameters to it.  This would mean only one build script bin related to `cfg_alises` would be built across your entire dependency tree or need to be audited.

**Comment by epage** [comment]
I feel like the use cases given might have some overlap with [global, mutually exclusive features](https://internals.rust-lang.org/t/pre-rfc-mutually-excusive-global-features/19618) and I wonder if there is a way to fit a higher level construct into that.

**Comment by heaths** [comment]
Another use case we have is to record the `rustc` version used to compile with our library that we telemeter, if enabled. Currently I don't see anything obvious recorded in ELF or PE/COFF executables that record the rustc version used - perhaps it's in the debug info, but that may not have been deployed - but perhaps making some basic info available in header or section data - perhaps the debug section - could be exposed at runtime. I admit I don't know much about ELF - Windows had been my primary dev env for decades - but looking at a release-build from rustc, it does look like GCC is recording quite a bit of build/version information so maybe it's warranted to add some rustc info? MSVC (and apparently clang on Windows now) also stores some linker info in the PE/COFF as well.

I mean, there's other ways as well like linking in function to get info, but stamping this in the executable might be useful to external tools as well. Just some thoughts.

**Comment by bjorn3** [comment]
> Currently I don't see anything obvious recorded in ELF or PE/COFF executables that record the rustc version used

The `.comment` section for ELF executables contains the version of rustc as well as many other tools that were involved in producing the executable. For example:

```
$ readelf --string-dump=.comment ~/.cargo/bin/rustup

String dump of section '.comment':
  [     0]  GCC: (GNU) 4.8.5 20150623 (Red Hat 4.8.5-44)
  [    2d]  GCC: (GNU) 9.5.0
  [    3e]  rustc version 1.77.2 (25ef9e3d8 2024-04-09)
  [    6a]  clang version 18.1.0rc
```

As for PE/COFF executables, it looks like the PDB debuginfo file will contain the rustc string. At least https://rust.godbolt.org/z/3zxrKehsK shows the `clang LLVM (rustc version 1.84.0 (9fc6b4312 2025-01-07))` string ending up in the `.debug$S` section of the object file.

**Comment by heaths** [comment]
Interesting. I ran `readelf -a <path>` and it didn't dump the `.comment` section, but doing what you did explicitly worked. Maybe `std` could expose that if there's enough demand.

As for PE/COFF, I expected this was in the `.pdb`. somewhere but it's rare symbols are deployed. What might be ideal is to actually store it in a debug directory like MSVC does, something to the effect of:

```
$ dumpbin /headers /section:.rdata <exe>

# ...
  Debug Directories

        Time Type        Size      RVA  Pointer
    -------- ------- -------- -------- --------
    678FF0B6 cv            4E 00003960     2960    Format: RSDS, {0466A304-9921-46F8-8636-239DB83AA58C}, 1, <path>.pdb
    678FF0B6 feat          14 000039B0     29B0    Counts: Pre-VC++ 11.00=0, C/C++=35, /GS=35, /sdl=1, guardN=34
    678FF0B6 coffgrp      30C 000039C4     29C4    4C544347 (LTCG)
    678FF0B6 iltcg          0 00000000        0
```

**Comment by LeonMatthesKDAB** [comment]
Another important use-case I want to mention is FFI (especially with C/C++), which probably broadly fits under the `codegen` category.

build scripts are encouraged for [bindgen](https://rust-lang.github.io/rust-bindgen/library-usage.html), [CXX](https://cxx.rs/build/cargo.html) and [CXX-Qt](https://kdab.github.io/cxx-qt/book/getting-started/4-cargo-executable.html).
Where CXX and CXX-Qt both rely on the [cc crate](https://docs.rs/cc/latest/cc/), which also encourages use in build scripts.

Especially in the case of cc/CXX/CXX-Qt, this means the build script invokes the C/C++ compiler.
This can be quite detrimental to compile time, as the ever-changing out dir requires a total rebuild of all C++ code even on simple changes.
Incremental builds are currently impossible for the C++ code.

Here are the timing results of rebuilding CXX-Qt after touching a single file in cxx-qt-gen:
[cargo-timing.zip](https://github.com/user-attachments/files/18746914/cargo-timing.zip)

In this example, the build scripts take up about 17.34s out of 20.5s (~85%).

**Comment by LeonMatthesKDAB** [comment]
@epage Regarding the out_dir issue, I think the issue that comes closest is #7197 .

This was closed years ago with the note that build scripts should take care of incremental builds themselves.
However, I think there still no concrete guideline for how to actually do that at this point?

The best practice for build scripts is that they should only write to their OUT_DIR.
However, new invocations of the build script (to my knowledge) have no way of accessing previous OUT_DIRs, which makes doing anything incrementally difficult.
It is also unclear when exactly artifacts could be reused from previous invocations, but that's likely an issue that's specific to each build script.

Should I create a new issue for this or re-open #7197 ?

With CXX-Qt concretely, we have vague plans to try our hands on this by combining the [`scratch`](https://docs.rs/scratch/latest/scratch/) directory with hashing of the environment and using sccache to cache the actual C++ compilation.
The largest issue with something like sccache at the moment is that sccache will include the full path of the file in its hash, which means sccache does not provide any benefit to files in the OUT_DIR.
This wouldn't need any changes in Cargo, but is also a pretty experimental solution to the problem.

**Comment by bjorn3** [comment]
Provided that the crate version and build configuration doesn't change, you should be getting the same OUT_DIR even when changing the source code of the crate.

**Comment by LeonMatthesKDAB** [comment]
> Provided that the crate version and build configuration doesn't change, you should be getting the same OUT_DIR even when changing the source code of the crate.

@bjorn3 You're right and I'm shocked that I didn't notice that before...
At least on my local development machine it works and I get the same OUT_DIR...

I'll have to check what is going on in our CI then, as that gets almost no cache hits.
Maybe the hash does end up being different there due to some environment variable set by Github Actions or something like that...

**Comment by qknight** [comment]
@epage I've considered a few typical use-cases for build.rs with implications to build purity (sandboxing).

If we had permissions like discussed in the issue below we could know if a project can be compiled locally at all by simply looking at the required capabilities. This is important for nix sandboxes but also for the time when cargo uses a sandbox concept in general.

For completeness I've also added the section with the declarative directory/file lists in the Cargo.toml - which are most interesting for the _Codegen_ category.

https://github.com/nixcloud/cargo/issues/6

**Comment by epage** [comment]
This issue is for discussing build script use cases that can be replaced with other features. For sandboxing, see https://github.com/rust-lang/cargo/issues/5720

**Comment by guineawheek** [comment]
[VCS metadata (e.g. Git hash/dirty state) should probably be exported on a per-crate basis by Cargo through `env!()`.](https://github.com/guineawheek/build-rs-gacha#shoveling-vcsversion-metadata-into-env) 

A lot of `build.rs` scripts shell out to `git` for this and there are extant footguns like "not all build contexts have the `.git` folder available". It's a common reason to pull in external dependencies in `build.rs` for shared implementations as well.

**Comment by epage** [comment]
@guineawheek want to create an issue for that where we can work through the design?

**Comment by weihanglo** [comment]
There is one relevant issue: <https://github.com/rust-lang/cargo/issues/11456>
