### ISSUE TITLE
Tracking issue for missing Iterator::size_hint implementations

### ISSUE THREAD

**Issue by Phlosioneer** [rust-lang/cargo#5211]
`size_hint()` can sometimes allow for more efficient memory allocations, and other good performance things.

I intend to make a PR to implement the trivial / easy ones, at least.

This list will be updated as I sort through for false-positives.

- [ ] [`Deps<'a>`](https://github.com/rust-lang/cargo/blob/d10ec661b06420654bbc4ed0ccd32295698aa1dc/src/cargo/core/resolver/mod.rs#L296) (#5272)
- [ ] [`DepsNotReplaced`](https://github.com/rust-lang/cargo/blob/d10ec661b06420654bbc4ed0ccd32295698aa1dc/src/cargo/core/resolver/mod.rs#L306) (#5272)
- [x] ~~[`SourcesMut<'a, 'src>`](https://github.com/rust-lang/cargo/blob/d10ec661b06420654bbc4ed0ccd32295698aa1dc/src/cargo/core/source/mod.rs#L155)~~ Never used.
- [ ] [`Members<'a, 'cfg>`](https://github.com/rust-lang/cargo/blob/d10ec661b06420654bbc4ed0ccd32295698aa1dc/src/cargo/workspace.rs#L766) (#5272)
- [x] ~~[`Tokenizer<'a>`](https://github.com/rust-lang/cargo/blob/d10ec661b06420654bbc4ed0ccd32295698aa1dc/src/cargo/util/cfg.rs#L200)~~ No efficient way to do this.
- [x] ~~[`PathAncestors<'a>`](https://github.com/rust-lang/cargo/blob/d10ec661b06420654bbc4ed0ccd32295698aa1dc/src/cargo/util/paths.rs#L179)~~ No easy way to do this.

I found them by running grep -r -n "impl.*\bIterator for \|fn size_hint" src > size_hint_todo.txt. Then, delete any pairs of an Iterator line followed by a size_hint line, and manually check the remaining Iterator lines for false positives.

**Comment by alexcrichton** [comment]
Thanks for the report! I'd want to make sure that there's actualy performance to gain here, very little in Cargo is performance sensitive and that which is has already been relatively heavily optimized.

**Comment by Phlosioneer** [comment]
Alright, I’ll check for that when taking a closer look at these.
