### ISSUE TITLE
Renaming dependencies in Cargo.toml

### ISSUE THREAD

**Issue by matklad** [rust-lang/cargo#5653]
Implementation PR: [#4953](https://github.com/rust-lang/cargo/pull/4953)

**Summary:**

With `cargo-features = ["rename-dependency"]` in Cargo.toml, you will be able to specify dependencies as `bar = { package = "foo", version = "0.1" }`. That adds dependency to `foo` package from `crates.io`, which will be visible as `extern crate bar`.

**Steps:**

- `cargo metadata` should include information about renames, https://github.com/rust-lang/cargo/issues/5583.

- outstanding bugs:
  - [x] rust-lang/rust#51259
  - [x] rust-lang/rust#51795
  - [x] rust-lang/rust#51796
  - [x] rust-lang/cargo#5753

- Figure out to do about --features on the command line? Does --features foo/bar imply the package foo or the crate that's renamed to foo? We probably want the latter, and that's probably buggy right now.

**Stabilization TODO:**

- move docs from https://github.com/rust-lang/cargo/blob/5845464cf92a348f95dc6b43133c017c37fcb684/src/doc/src/reference/unstable.md#rename-dependency to proper location.
- remove feature gate

**Comment by matklad** [comment]
Note: preferably, this should be stabilized before or in tandem with https://github.com/rust-lang/rust/issues/44660

**Comment by ehuss** [comment]
Some bugs have been noted recently:
- rust-lang/rust#51259
- rust-lang/rust#51795
- rust-lang/rust#51796

Also, there is another tracking issue for this: #5422

**Comment by matklad** [comment]
Excellent, thanks @ehuss! I've updated the original issue.

**Comment by withoutboats** [comment]
Added another bug: #5753.

**Comment by TheDan64** [comment]
#51796 and #5753 seem to be fixed and closed according to those threads. Can the checklist be updated?

**Comment by Nemo157** [comment]
New bug with optional renamed dependencies once published: https://github.com/rust-lang/cargo/issues/5962

**Comment by TheDan64** [comment]
Anecdotally, I'd like to share my experience trying out this really cool feature in my project, [inkwell](https://github.com/TheDan64/inkwell), which is a safe wrapper over LLVM:

In inkwell we support multiple LLVM versions, by using feature flags mutually exclusively. This lead us to having version branches which only differ from master by setting a default version feature flag and a llvm-sys dependency version.

I was hoping this cargo feature could greatly simplify this approach and allow us to simply have a master branch with this kind of configuration:
```toml
[features]
default = []
llvm3-6 = []
# ...
llvm7-0 = []

[dependencies]
llvm-sys-36 = { package = "llvm-sys", version = "36.2" }
# ...
llvm-sys-70 = { package = "llvm-sys", version = "70.0" }
```

```rust
// lib.rs
#[cfg(feature = "llvm3-6")]
extern crate llvm_sys_36 as llvm_sys;
// ...
#[cfg(feature = "llvm7-0")]
extern crate llvm_sys_70 as llvm_sys;

use llvm_sys::X;
```

I got the distinct impression that this should work, however, in practice there's one massive problem which seems obvious in retrospect: linker conflicts. Indeed, cargo ends up spitting out this sort of error message:
```shell
    Updating crates.io index
error: failed to select a version for `llvm-sys`.
    ... required by package `inkwell v0.1.0 (/mnt/d/LinuxData/repos/inkwell)`
versions that meet the requirements `^50.2` are: 50.2.0

the package `llvm-sys` links to the native library `llvm`, but it conflicts with a previous package which links to `llvm` as well:
package `llvm-sys v40.2.0`
    ... which is depended on by `inkwell v0.1.0 (/mnt/d/LinuxData/repos/inkwell)`

failed to select a version for `llvm-sys` which could resolve this conflict
```

Anyway, I totally understand my use case here is very very niche and possibly misusing the intent of rust feature flags and/or this feature. I just thought I'd mention that it would be nice to be able to let cargo know you'd like to use different versions of a crate in a mutually exclusive way, if at all possible, so that you can avoid such linker errors when using ffi/-sys crates with this feature.

**Comment by withoutboats** [comment]
@TheDan64 I notice in your code sample you didn't make those dependencies optional? I don't know that that will actually impact linking, but it seems like making them optional and only available when the feature is turned on might help your situation.

**Comment by TheDan64** [comment]
@withoutboats thanks for the idea! I didn't even think about that. Unfortunately I still end up with the same linking error, which is surprising.

**Comment by Nemo157** [comment]
@TheDan64 testing a similar situation (two optional dependencies that both link against the same native library, neither actually enabled) without using renaming gives the same error. So _if_ that is a supported usecase (I'm not sure it is since an optional dependency is a feature, and features are supposed to be purely additive, but enabling both would have to give the linking error) then using renaming with it seems like it should work (and likely would Just Work<sup>:tm:</sup>).

I'm surprised I can't find an issue about that situation, might be worth opening one to clarify whether it should be possible.

**Comment by alexcrichton** [comment]
Thanks for the comment @TheDan64! I think though that's unrelated to this in that crate renaming is probably working but you're blocked by a different error in Cargo. Unfortunately Cargo has to pessimistically assume that you could enable all the features all the time, so it's not possible to resolve that crate graph as it'd bring in two versions of LLVM

**Comment by SimonSapin** [comment]
It would be nice to stabilize this feature and backport it to 1.31 beta before the code freeze https://internals.rust-lang.org/t/beta-1-31-code-freeze/8825, since that is the first version shipping with the 2018 edition.

**Comment by Nemo157** [comment]
And there is a published version of `futures-preview` [using this feature](https://github.com/rust-lang-nursery/futures-rs/blob/0.3.0-alpha.9/futures-util/Cargo.toml#L35) without issues ([this time](https://github.com/rust-lang-nursery/futures-rs/issues/1247)), so it has been tested in the wild on nightly.

**Comment by alexcrichton** [comment]
Thanks for the reminder @SimonSapin, I've posted that as https://github.com/rust-lang/cargo/pull/6311
