### ISSUE TITLE
Tracking issue for cache-messages

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#6986]
Implementation PR: #6933 
Documentation: https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#cache-messages

**Summary**
Caches the output from `rustc` so that future runs can redisplay previous warnings. 

```
cargo +nightly check -Z cache-messages
```

This also fixes some interleaved output from parallel compilers, like #6848.

**Unresolved issues**
- [x] `short` messages are not supported.  Either the rustc JSON output needs to include an additional field with the `short` rendered form, or cargo and rustc need to share a diagnostics rendering library and the JSON format extended to support that.
- [x] rustdoc does not support `--json-rendered=termcolor`, so its output is currently uncolored.
- [x] `--json-rendered` needs to be stabilized (or redesigned, see first point).
- [x] A major goal of properly redisplaying clippy warnings is not yet finished. Clippy shares the same fingerprint with `cargo check`.  The fingerprint or metadata hash needs to include that clippy is in use to fix this. Also, the clippy wrapper needs to only be applied to member crates, not registry dependencies.

**Comment by apiraino** [comment]
@ehuss now that #6933 and #7450 are merged, is there another main issue to track on this topic or it's done (i.e. :champagne:)?

Thanks!

**Comment by ehuss** [comment]
It should be done. It should be in nightly the day after https://github.com/rust-lang/rust/pull/65445 lands.

**Comment by BatmanAoD** [comment]
🎉
