### ISSUE TITLE
Tracking Issue for `cargo rustc --print=VAL`

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo#9357]
**Summary**

Original issue: #8923
Implementation: #9002

`cargo rustc --print=VAL` forwards the `--print` flag to `rustc` in order to extract information from `rustc`. This runs `rustc` with the corresponding [`--print`](https://doc.rust-lang.org/rustc/command-line-arguments.html#--print-print-compiler-information) flag, and then immediately exits without compiling. Exposing this as a cargo flag allows cargo to inject the correct target and RUSTFLAGS based on the current configuration.

The primary use case is to run `cargo rustc --print=cfg` to get config values for the appropriate target and influenced by any other RUSTFLAGS.

**Unresolved issues**

(These aren't necessarily blockers, just random thoughts about the current design.)

* [ ] I think `cfg` is the only value that is worth printing. It is not clear from a UI perspective if it makes sense to expose the other values, since several will just fail or don't add anything different than running `rustc` directly. Forwarding the print value to rustc is more flexible and probably fine, though it seems like it could cause confusion.
* [ ] The intended use case of `--print=cfg` means anyone using it needs to implement a parser for the ad-hoc format. The original implementation parsed it and returned JSON, which might be easier to consume? There was some back-and-forth discussion on the PR about this, and possibly using a more general purpose subcommand (like `cargo config`) for "expose internal information". It might be worth considering that more.
* [ ] The behavior with multiple `--target` flags is a little strange.
* [ ] Profiles are ignored. This has historically caused confusion for people (for things like `debug_assertions`). However, all of cargo ignores profiles for the intended use case (`--print=cfg`). It's not clear what this should do.

**Future extensions**

**About tracking issues**

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

**Comment by volks73** [comment]
Thank you for creating this issue to track stabilization. I just wanted to briefly comment about a couple of the unresolved issues (not sure if I should be creating separate issues for each of these):

>- [ ] The intended use case of `--print=cfg` means anyone using it needs to implement a parser for the ad-hoc format. The original implementation parsed it and returned JSON, which might be easier to consume? There was some back-and-forth discussion on the PR about this, and possibly using a more general purpose subcommand (like `cargo config`) for "expose internal information". It might be worth considering that more.

I have created the [cargo-rustc-cfg](https://crates.io/crates/cargo-rustc-cfg) crate so that others do not need to create a parser each time the output of the `--print=cfg` option is needed. This would avoid needing to create (and maintain) a JSON-based output format.

Please note, the release version (v0.2.0) was created and released prior to the existence of the `cargo rustc --print cfg` feature, but the version available in the `main` branch of the [repository](https://github.com/volks73/cargo-rustc-cfg) does utilize the new feature. I just haven't had a chance to release the new version, and I wasn't sure about releasing a "nightly only" version of the crate on crates.io and doing so before a feature was stabilized.

>- [ ] The behavior with multiple `--target` flags is a little strange.

Could you expand on the strangeness of the behavior? Output for each specified `--target` is printed and delimited with an empty line. Granted, I only considered the `--print=cfg` variant and not other options for printing.

**Comment by ehuss** [comment]
> Could you expand on the strangeness of the behavior?

Just that the blank line solution seems potentially brittle. It assumes the data will never have blank lines. Also, it may be difficult to correlate the output with the actual targets (let's say the targets are driven by a config file).  Not big issues, and multiple targets is a very advanced use case, so it is unlikely to be used often.

**Comment by volks73** [comment]
Thank you for explanation and see the issue with using the blank lines to delimit the output for multiple targets. There appears to be two issues at play: (1) delimiting the output and (2) associating output with targets. 

A `--delimiter=<value>` like option could be added to address (1) delimiting the output by changing the blank line to be a row of characters, such as `--delimiter="-"` would print 80 `-` characters. Or, simply decide on a non-blank line delimiter that would have a relatively low likelihood of existing in future output from the underlying `rustc --print cfg` command.

As for (2) associating output with targets, it might be possible to enforce the order specified at the CLI to the order that is printed. Currently, I believe there is no guarantees on the output order nor order for the incoming multiple `--target` options. The output is currently a "raw dump" of the rustc output, which does not include a line or key-value pair for the target tuple. A "title" line could be added that does include the tuple and maybe this can serve a dual purpose as the delimiter of output as well.

However, changing the output to a more structured format, such as JSON, resolves both issues with minimal changes to the CLI and implementation. The `--print=<val>` would need to be changed to `--print-cfg` to avoid complications with printing other values from `rustc`, as mentioned in the first bullet point, unless a generic JSON format can be designed for any output from `rustc --print <val>`.

Do you foresee rolling this into `cargo config` (#9301)? For example, a `cargo config get rustc.cfg` command?

**Comment by xd009642** [comment]
Just a note after the changes to proc macro crates and linking it seems that `rustc --print=target-libdir` is now needed for some tools like cargo tarpaulin

**Comment by polarathene** [comment]
Over 5 years since the support was merged, it is still gated behind `-Z unstable-options`. I came across this rather confusing message after adding that:

```console
$ cargo +nightly rustc -Z unstable-options --target=x86_64-unknown-linux-none --print=target-spec-json
error: the `-Z unstable-options` flag must also be passed to enable the `target-spec-json` print option
```

I learned about the use of `--`, which passes args to `rustc`, but if you were to wedge that in after `rustc` it would perform a build (_which the feature in cargo was intended to avoid_).

Turns out that `rustc` feature gates `--print=target-spec-json` behind it's own `-Z unstable-options`. Presumably `cargo rustc` should be forwarding `-Z unstable-options` to `rustc` too? (_although `--print=cfg` is stable on `rustc` but not `cargo rustc` where the overlap and inconsistency could be a bit confusing_ 😅)

---

So for anybody else landing here, the correct call for `--print=target-spec-json` has two `-Z unstable options` like this:

```bash
cargo +nightly rustc -Z unstable-options --target=x86_64-unknown-linux-none --print=target-spec-json -- -Z unstable-options
```
